version: '3'

services:
  mysql_dbms: 
    image: mysql:8.0.26
    container_name: mysql
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gql_jwt