version: '3'

services:
  mysql-dbms:
    image: mysql:8.0.26
    container_name: simple-go-graphql-jwt-roles-db
    restart: on-failure
    networks:
      - simple-go-graphql-jwt-roles-net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gql_jwt

networks:
  simple-go-graphql-jwt-roles-net: {}
