version: '3'

services:
  app:
    image: irdaislakhuafa/simple-go-graphql-jwt-roles:latest
    container_name: simple-go-graphql-jwt-roles-app
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - simple-go-graphql-jwt-roles-net
    depends_on:
      - app-db

  app-db:
    image: mysql:8.0.26
    container_name: simple-go-graphql-jwt-roles-db
    restart: on-failure
    networks:
      - simple-go-graphql-jwt-roles-net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gql_jwt

networks:
  simple-go-graphql-jwt-roles-net: {}
