name: Simple Go GraphQL JWT and Roles

on: 
  push: 
    branches: 
      - master
      - dev
  pull_request: 
    branches: 
      - master
      - dev

jobs: 
  build: 
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository to github enviroment
        uses: actions/checkout@v1

      - name: Setup Golang enviroment
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Build app
        run: go build -o app main.go && ./app
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build image and push to Dockerhub
        uses: docker/build-push-action@v2
        with: 
          context: ./env/
          push: true
          tags: irdaislakhuafa/simple-go-graphql-jwt-roles:latest
